version: '3.9'
services:
  web:
    build: .
    command: ["/usr/bin/supervisord", "-c", "/app/supervisord.conf"]
    volumes:
      - ./lab2:/app
      - images_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DJANGO_DEBUG=1
      - DATABASE_NAME=mydb
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_HOST=db
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=user
      - RABBIT_PASS=password

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build: .
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=user
      - RABBIT_PASS=password
      - MEDIA_ROOT=/app/media
    volumes:
      - images_data:/app/media

volumes:
  db_data:
  images_data:
